---
credentials:
  username: (( vault tweed.vault "/users/" $BINDING ":username" ))
  password: (( vault tweed.vault "/users/" $BINDING ":password" ))
  database: (( vault tweed.vault "/db:name" ))

  hosts: (( grab infra.nodes ))
  host: (( grab infra.nodes[0] ))
  port: (( grab infra.port ))
